name = "erplogistics"
main = ".open-next/worker.js"
# 🚀 建议将日期改新一点，以支持最新的 Assets 特性
compatibility_date = "2024-11-18" 
compatibility_flags = ["nodejs_compat"]

# ❌ 删掉原来的 [site] 及其 bucket 
# ✅ 改用现代化的 [assets] 
[assets]
directory = ".open-next/assets"
binding = "ASSETS"


[vars]
NODE_ENV = "production"
API_KEY = "076311"

[[d1_databases]]
binding = "logistics_db"
database_name = "logistics-db"
database_id = "32079584-2dd5-435d-bd3b-7fd971fda320"