#:schema node_modules/wrangler/config-schema.json

name = "erplogistics"   # 👈 改成你要访问的名字
main = ".open-next/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "logistics_db"
database_name = "logistics-db"
database_id = "32079584-2dd5-435d-bd3b-7fd971fda320"